---

- import_tasks: jitsi-meet.yml
- import_tasks: prosody.yml
- import_tasks: ui_customization.yml
- import_tasks: nginx.yml

- name: Generate logrotate configs
  template:
    src: logrotate.d/{{ item }}.j2
    dest: /etc/logrotate.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - jicofo
    # - jitsi-videobridge https://github.com/systemli/ansible-role-jitsi-meet/issues/33
    - nginx
    - prosody
